apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  selector:
    matchLabels:
      app: sentence
  template:
    metadata:
      labels:
        app: sentence
    spec:
      containers:
        - name: sentence
          image: f5demosprivate.azurecr.io/ms-build-demo/sentence
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: ""
            - name: NAMESPACE
              value: "ms-build-demo"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sentence
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  type: ClusterIP
  selector:
    app: sentence
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colors
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  selector:
    matchLabels:
      app: colors
  template:
    metadata:
      labels:
        app: colors
    spec:
      containers:
        - name: colors
          image: f5demosprivate.azurecr.io/ms-build-demo/colors
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: ""
            - name: NAMESPACE
              value: "ms-build-demo"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: colors
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  type: ClusterIP
  selector:
    app: colors
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjectives
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  selector:
    matchLabels:
      app: adjectives
  template:
    metadata:
      labels:
        app: adjectives
    spec:
      containers:
        - name: adjectives
          image: f5demosprivate.azurecr.io/ms-build-demo/adjectives
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: ""
            - name: NAMESPACE
              value: "ms-build-demo"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: adjectives
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  type: ClusterIP
  selector:
    app: adjectives
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
        - name: animals
          image: f5demosprivate.azurecr.io/ms-build-demo/animals
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: ""
            - name: NAMESPACE
              value: "ms-build-demo"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: animals
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  type: ClusterIP
  selector:
    app: animals
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  selector:
    matchLabels:
      app: locations
  template:
    metadata:
      labels:
        app: locations
    spec:
      containers:
        - name: locations
          image: f5demosprivate.azurecr.io/ms-build-demo/locations
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: ""
            - name: NAMESPACE
              value: "ms-build-demo"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: locations
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  type: ClusterIP
  selector:
    app: locations
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backgrounds
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  selector:
    matchLabels:
      app: backgrounds
  template:
    metadata:
      labels:
        app: backgrounds
    spec:
      containers:
        - name: backgrounds
          image: f5demosprivate.azurecr.io/ms-build-demo/backgrounds
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: ""
            - name: NAMESPACE
              value: "ms-build-demo"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backgrounds
  annotations:
    ves.io/app-type: ves-io-ms-build-demo-sentence-frontend
spec:
  type: ClusterIP
  selector:
    app: backgrounds
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-nginx
          image: f5demosprivate.azurecr.io/ms-build-demo/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: ""
            - name: NAMESPACE
              value: "ms-build-demo"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
